apiVersion: v1 
kind: Service
metadata: 
  name: nginx
spec:
  selector:
    purpose: blue-green
    project: safety
    color: blue
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port