apiVersion: v1 
kind: Service
metadata: 
  name: nginx
spec:
  selector:
    purpose: blue-green
    project: safety
    color: green
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port

## once preview service working fine we are update main service color label to green